export const TYPE_CHART: Record<string, Record<string, number>> = {
  pokemon_type_normal: {
    pokemon_type_rock: 0.625,
    pokemon_type_ghost: 0.39,
    pokemon_type_steel: 0.625,
  },
  pokemon_type_fire: {
    pokemon_type_fire: 0.625,
    pokemon_type_water: 0.625,
    pokemon_type_grass: 1.6,
    pokemon_type_ice: 1.6,
    pokemon_type_bug: 1.6,
    pokemon_type_rock: 0.625,
    pokemon_type_dragon: 0.625,
    pokemon_type_steel: 1.6,
  },
  pokemon_type_water: {
    pokemon_type_fire: 1.6,
    pokemon_type_water: 0.625,
    pokemon_type_grass: 0.625,
    pokemon_type_ground: 1.6,
    pokemon_type_rock: 1.6,
    pokemon_type_dragon: 0.625,
  },
  pokemon_type_electric: {
    pokemon_type_water: 1.6,
    pokemon_type_electric: 0.625,
    pokemon_type_grass: 0.625,
    pokemon_type_ground: 0.39,
    pokemon_type_flying: 1.6,
    pokemon_type_dragon: 0.625,
  },
  pokemon_type_grass: {
    pokemon_type_fire: 0.625,
    pokemon_type_water: 1.6,
    pokemon_type_grass: 0.625,
    pokemon_type_poison: 0.625,
    pokemon_type_ground: 1.6,
    pokemon_type_flying: 0.625,
    pokemon_type_bug: 0.625,
    pokemon_type_rock: 1.6,
    pokemon_type_dragon: 0.625,
    pokemon_type_steel: 0.625,
  },
  pokemon_type_ice: {
    pokemon_type_fire: 0.625,
    pokemon_type_water: 0.625,
    pokemon_type_grass: 1.6,
    pokemon_type_ice: 0.625,
    pokemon_type_ground: 1.6,
    pokemon_type_flying: 1.6,
    pokemon_type_dragon: 1.6,
    pokemon_type_steel: 0.625,
  },
  pokemon_type_fighting: {
    pokemon_type_normal: 1.6,
    pokemon_type_ice: 1.6,
    pokemon_type_poison: 0.625,
    pokemon_type_flying: 0.625,
    pokemon_type_psychic: 0.625,
    pokemon_type_bug: 0.625,
    pokemon_type_rock: 1.6,
    pokemon_type_ghost: 0.39,
    pokemon_type_dark: 1.6,
    pokemon_type_steel: 1.6,
    pokemon_type_fairy: 0.625,
  },
  pokemon_type_poison: {
    pokemon_type_grass: 1.6,
    pokemon_type_poison: 0.625,
    pokemon_type_ground: 0.625,
    pokemon_type_rock: 0.625,
    pokemon_type_ghost: 0.625,
    pokemon_type_steel: 0.39,
    pokemon_type_fairy: 1.6,
  },
  pokemon_type_ground: {
    pokemon_type_fire: 1.6,
    pokemon_type_electric: 1.6,
    pokemon_type_grass: 0.625,
    pokemon_type_poison: 1.6,
    pokemon_type_flying: 0.39,
    pokemon_type_bug: 0.625,
    pokemon_type_rock: 1.6,
    pokemon_type_steel: 1.6,
  },
  pokemon_type_flying: {
    pokemon_type_electric: 0.625,
    pokemon_type_grass: 1.6,
    pokemon_type_fighting: 1.6,
    pokemon_type_bug: 1.6,
    pokemon_type_rock: 0.625,
    pokemon_type_steel: 0.625,
  },
  pokemon_type_psychic: {
    pokemon_type_fighting: 1.6,
    pokemon_type_poison: 1.6,
    pokemon_type_psychic: 0.625,
    pokemon_type_dark: 0.39,
    pokemon_type_steel: 0.625,
  },
  pokemon_type_bug: {
    pokemon_type_fire: 0.625,
    pokemon_type_grass: 1.6,
    pokemon_type_fighting: 0.625,
    pokemon_type_poison: 0.625,
    pokemon_type_flying: 0.625,
    pokemon_type_psychic: 1.6,
    pokemon_type_ghost: 0.625,
    pokemon_type_dark: 1.6,
    pokemon_type_steel: 0.625,
    pokemon_type_fairy: 0.625,
  },
  pokemon_type_rock: {
    pokemon_type_fire: 1.6,
    pokemon_type_ice: 1.6,
    pokemon_type_fighting: 0.625,
    pokemon_type_ground: 0.625,
    pokemon_type_flying: 1.6,
    pokemon_type_bug: 1.6,
    pokemon_type_steel: 0.625,
  },
  pokemon_type_ghost: {
    pokemon_type_normal: 0.39,
    pokemon_type_psychic: 1.6,
    pokemon_type_ghost: 1.6,
    pokemon_type_dark: 0.625,
  },
  pokemon_type_dragon: {
    pokemon_type_dragon: 1.6,
    pokemon_type_steel: 0.625,
    pokemon_type_fairy: 0.39,
  },
  pokemon_type_dark: {
    pokemon_type_fighting: 0.625,
    pokemon_type_psychic: 1.6,
    pokemon_type_ghost: 1.6,
    pokemon_type_dark: 0.625,
    pokemon_type_fairy: 0.625,
  },
  pokemon_type_steel: {
    pokemon_type_fire: 0.625,
    pokemon_type_water: 0.625,
    pokemon_type_electric: 0.625,
    pokemon_type_ice: 1.6,
    pokemon_type_rock: 1.6,
    pokemon_type_steel: 0.625,
    pokemon_type_fairy: 1.6,
  },
  pokemon_type_fairy: {
    pokemon_type_fire: 0.625,
    pokemon_type_fighting: 1.6,
    pokemon_type_poison: 0.625,
    pokemon_type_dragon: 1.6,
    pokemon_type_dark: 1.6,
    pokemon_type_steel: 0.625,
  },
}
