export const TYPE_COLORS: Record<string, string> = {
  pokemon_type_normal:   '#A8A878',
  pokemon_type_fire:     '#F08030',
  pokemon_type_water:    '#6890F0',
  pokemon_type_electric: '#F8D030',
  pokemon_type_grass:    '#78C850',
  pokemon_type_ice:      '#98D8D8',
  pokemon_type_fighting: '#C03028',
  pokemon_type_poison:   '#A040A0',
  pokemon_type_ground:   '#E0C068',
  pokemon_type_flying:   '#A890F0',
  pokemon_type_psychic:  '#F85888',
  pokemon_type_bug:      '#A8B820',
  pokemon_type_rock:     '#B8A038',
  pokemon_type_ghost:    '#705898',
  pokemon_type_dragon:   '#7038F8',
  pokemon_type_dark:     '#705848',
  pokemon_type_steel:    '#B8B8D0',
  pokemon_type_fairy:    '#EE99AC',
}

export const TYPE_COLORS_PLAIN: Record<string, string> = {
  Normal:   '#A8A878',
  Fire:     '#F08030',
  Water:    '#6890F0',
  Electric: '#F8D030',
  Grass:    '#78C850',
  Ice:      '#98D8D8',
  Fighting: '#C03028',
  Poison:   '#A040A0',
  Ground:   '#E0C068',
  Flying:   '#A890F0',
  Psychic:  '#F85888',
  Bug:      '#A8B820',
  Rock:     '#B8A038',
  Ghost:    '#705898',
  Dragon:   '#7038F8',
  Dark:     '#705848',
  Steel:    '#B8B8D0',
  Fairy:    '#EE99AC',
}

export const TYPE_LABELS_PT: Record<string, string> = {
  pokemon_type_normal:   'Normal',
  pokemon_type_fire:     'Fogo',
  pokemon_type_water:    'Água',
  pokemon_type_electric: 'Elétrico',
  pokemon_type_grass:    'Grama',
  pokemon_type_ice:      'Gelo',
  pokemon_type_fighting: 'Lutador',
  pokemon_type_poison:   'Venenoso',
  pokemon_type_ground:   'Terra',
  pokemon_type_flying:   'Voador',
  pokemon_type_psychic:  'Psíquico',
  pokemon_type_bug:      'Inseto',
  pokemon_type_rock:     'Pedra',
  pokemon_type_ghost:    'Fantasma',
  pokemon_type_dragon:   'Dragão',
  pokemon_type_dark:     'Sombrio',
  pokemon_type_steel:    'Aço',
  pokemon_type_fairy:    'Fada',
}

export const RAID_LEVEL_LABELS: Record<string, string> = {
  lvl1:           '1★',
  lvl3:           '3★',
  lvl5:           '5★ / Lendário',
  mega:           'Mega',
  legendary_mega: 'Mega Lendário',
  ultra_beast:    'Ultra Beast',
  shadow_lvl1:    'Sombrio 1★',
  shadow_lvl3:    'Sombrio 3★',
  shadow_lvl5:    'Sombrio 5★',
  ex:             'EX',
}

export const CLASS_LABELS_PT: Record<string, string> = {
  POKEMON_CLASS_LEGENDARY:   'Lendário',
  POKEMON_CLASS_MYTHIC:      'Mítico',
  POKEMON_CLASS_ULTRA_BEAST: 'Ultra Beast',
}
